docmost/docmost

apps/client/package.json
apps/client/src/features/page/components/header/page-header-menu.tsx
apps/client/src/lib/config.ts
apps/server/package.json
package.json

This PR fixes the `APP_URL` usage on the frontend. The `APP_URL` is useful for building email links.
With this update, the frontend now relies on `window.location.host` when not in VITE dev mode. 
Fixes https://github.com/docmost/docmost/issues/28 and the issue mentioned on [HN](https://news.ycombinator.com/item?id=40834594).

client: fix APP_URL usage

---

apps/client/src/lib/api-client.ts
apps/client/vite.config.ts
apps/server/src/main.ts

We can use the devServer proxy option in Vite to avoid needing a CORS exception for development

CORS setup and Vite devServer proxy

---

apps/server/src/integrations/storage/drivers/s3.driver.ts
apps/server/src/integrations/storage/providers/storage.provider.ts
apps/server/src/integrations/storage/storage.service.ts

This PR makes provision to support `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
You can decide to either use `AWS_S3_ACCESS_KEY_ID` and `AWS_S3_SECRET_ACCESS_KEY` or 
`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`. 
The `AWS_S3_` prefixed one will take precedence if present.
See #56 for why we need this.

Add support for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables

---

apps/server/src/integrations/environment/environment.service.ts
apps/server/src/integrations/mail/providers/mail.provider.ts

Only configure auth object in smtp config if user and password are provided. If no auth object is defined, [nodemailer assumes the connection is already authenticated](https://nodemailer.com/smtp/#authentication).
Also exposed the secure config option.

add STMP_SECURE and changed auth config

---

apps/server/src/core/workspace/services/workspace-invitation.service.ts

The email says "${invitedUserName} has accepted your invitation ...", so it makes more sense to send it to the inviter instead of the invitee.

fix: send "invitation accepted" email to inviter

---

apps/server/src/core/auth/services/token.service.ts

Use the environment service for the `JWT_TOKEN_EXPIRES_IN` value instead of `30d` hardcoded.

fix: use environment service for refresh token's expiration

---

apps/server/src/integrations/health/redis.health.ts

I have both Docker and Uptime Kuma pinging the `/health` endpoint and after a few days my tiny VPS explodes with errors like:
```
docmost-1  | [ioredis] Unhandled error event: ReplyError: ERR max number of clients reached
docmost-1  |     at parseError (/app/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
docmost-1  |     at parseType (/app/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14)
```
Turns out that, if we don't disconnect the Redis client, they keep accumulating and don't timeout by default. To verify this in practice:
```
$ curl http://localhost:3000/api/health
{"status":"ok","info":{"database":{"status":"up"},"redis":{"status":"up"}},"error":{},"details":{"database":{"status":"up"},"redis":{"status":"up"} …
```

fix: disconnect Redis health checker

---

apps/client/src/features/editor/components/math/math.module.css

Setting the containers overflow-x rule to auto removed the scrollbar when not needed, but allows it to popup when needed.
Change confirmed to hide scrollbar and show if equation does not fit the width on (tested with responsive design mode):
- Chromium 126.0.6478.126
- Firefox 128.0.3 (64-bit)
Aims to fix (#292)

fix: horizontal scrollbar always shown on math block

---

apps/client/src/features/editor/styles/task-list.css

Labels for task list items are not aligned properly. The commit adds flex and align-items properties to the labels so that the labels are displayed vertically to the center of the parent element
Before:
```
ul[data-type=taskList] li>label {
flex: 0 0 auto;
margin-right: .5rem;
-webkit-user-select: none;
user-select: none;
}
```
After:
```
ul[data-type=taskList] li>label {
flex: 0 0 auto;
margin-right: .5rem;
-webkit-user-select: none;
user-select: none;
display: flex;
align-items: center;
}
```

fix: Add alignment styles for task list items

---

apps/client/src/features/editor/components/math/math.module.css

Removed CSS rules setting fonts for math blocks andd inline elements, preventing KaTeX to use bold math fonts in special cases.
Refs: #376

fix: removed font overwrite for KaTeX elements

---

package.json
patches/react-arborist@3.4.0.patch
pnpm-lock.yaml

In this PR, we patch the [react-arborist](https://www.npmjs.com/package/react-arborist) (used for space tree) package to remove the backspace delete shortcut key.
Closed https://github.com/docmost/docmost/issues/372.

fix: remove space tree delete shortcut key

---

Dockerfile

Hi.
I've added missing COPY patches in Dockerfile.
without COPY patches, docker build must be failed.
```
0.586 Scope: all 3 workspace projects
0.742  ENOENT  ENOENT: no such file or directory, open '/app/patches/react-arborist@3.4.0.patch'
0.742 
0.742 pnpm: ENOENT: no such file or directory, open '/app/patches/react-arborist@3.4.0.patch'
0.742     at async open (node:internal/fs/promises:637:25)
0.742     at async Object.readFile (node:internal/fs/promises:1246:14)
0.742     at async createBase32HashFromFile (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:10395:23)
0.742     at async /usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:140353:17
0.742     at async /usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:140330:24
0.742     at async Promise.all (index 0)
0.742     at async pMapValue …
```

add `COPY patches` on Dockerfile

---

apps/client/src/features/page/components/breadcrumbs/breadcrumb.module.css

Hopefully fixes #410.
Before: 
After:

Fix: breadcrumb clipping

---

apps/server/src/collaboration/collaboration.gateway.ts
apps/server/src/common/helpers/utils.ts
apps/server/src/integrations/queue/queue.module.ts

Fix to properly support redis database numbers.
`REDIS_URL=redis://127.0.0.1:6379/1`
Closes https://github.com/docmost/docmost/issues/498.

fix: properly support redis database numbers

---

apps/client/src/components/icons/google-sheets-icon.tsx
apps/client/src/components/icons/index.ts
apps/client/src/features/editor/components/embed/providers.ts
apps/client/src/features/editor/components/slash-menu/menu-items.ts

This commit adds "Google Sheets" in the editor command menu and allows users to embed published Google Sheets docs.
Note that the URL to embed should be attained by "publishing" Google Sheets docs, i.e. "File" -> "Share" -> "Publish to web" in Google Sheets menu.

feat: google sheets embed

---

apps/client/src/components/ui/emoji-picker.tsx
apps/client/src/features/page/tree/atoms/node-id-atom.ts
apps/client/src/features/page/tree/components/space-tree.tsx

Resolve: #570 
The solution I tried is to use a shared variable to save the nodeId. I used the Atom state management system so that all components of the pages can access it. If we click on an emoji page, we store the nodeId in the Atom, and this will trigger the list of emojis to open. If we click again on the same page, we store null to close it.
Please review this approach, and if you know a better solution, let me know.

Fix: Ensure only one emoji list appears 

---

package.json
pnpm-lock.yaml

Fix punycode DeprecationWarning error by overriding the jsdom (24.1.1-> 25.0.1) version used by turndown.
The error came from the  "tough-cookie" package used by jsdom (fixed here https://github.com/jsdom/jsdom/pull/3776)

fix: punycode DeprecationWarning error

---

.env.example
apps/server/src/integrations/environment/environment.validation.ts

For better security, we are enforcing a minimum of 32-character length for the `APP_SECRET` env variable.

fix: enforce 32-character minimum length for APP_SECRET

---

apps/client/src/features/space/components/sidebar/switch-space.tsx

This PR fixes an issue where the popover in the SwitchSpace component does not close when clicking outside.
Since SwitchSpace is a controlled component, the state needs to be toggled via onChange. This change ensures that the popover properly closes when expected.
Reference: [mantinedev/mantine#7019](https://github.com/mantinedev/mantine/issues/7019)

Fix: Close Popover When Clicking Outside in SwitchSpace Component

---

apps/server/src/core/workspace/services/workspace-invitation.service.ts

The password is hashed twice in acceptInvitation func and in insertUser func so we get an error when we compare the password hash when we login after invitation.

fix: accept invitation password hashing

---

apps/server/src/collaboration/collaboration.module.ts
apps/server/src/collaboration/server/collab-app.module.ts
apps/server/src/collaboration/server/collab-main.ts
apps/server/src/collaboration/server/collaboration.controller.ts
apps/server/src/main.ts

Introduce `api/collab/stats` endpoint to the standalone collab server.
This shows the total connections and open document count.
Ideally, this should be a protected endpoint.
The endpoint is registered if `COLLAB_SHOW_STATS=true` is set.

feat: add stats to standalone collab server

---

apps/server/src/integrations/export/export.service.ts

Removing colgroup tags in html string before exporting in markdown
```
From isHeadingRow() function in @joplin/turndown-plugin-gfm :
// A tr is a heading row if:
// - the parent is a THEAD
// - or if its the first child of the TABLE or the first TBODY (possibly
//   following a blank THEAD)
// - and every cell is a TH
````
before -> after

fix: table header in markdown export

---

apps/client/src/features/editor/extensions/markdown-clipboard.ts
packages/editor-ext/src/lib/markdown/utils/marked.utils.ts

Markdown pasted from VSCode is now transformed into standard ProseMirror nodes instead of being wrapped in a markdown code block.
Fix for https://github.com/docmost/docmost/issues/818.

fix: VSCode markdown pasting

---

apps/client/src/components/ui/emoji-picker.tsx

Added attribute to make emoji-picker automatically focus the search bar when opened.
Before:
After:

feat: auto focus emoji-picker search when opened

---

apps/server/src/collaboration/extensions/persistence.extension.ts
apps/server/src/core/page/page.controller.ts
apps/server/src/core/page/services/page.service.ts
apps/server/src/database/database.module.ts
apps/server/src/database/migrations/20250327T145832-add-collaborators-to-pages.ts
apps/server/src/database/migrations/20250327T145832-add-contributorIds-to-pages.ts
apps/server/src/database/repos/page/page.repo.ts
apps/server/src/database/types/db.d.ts

In this PR, we introduced changes to keep track of users who contribute to a page.
We have added a new `contributorIds` column to the `pages` table.

feat: keep track of page contributors

---

apps/client/src/features/page-history/components/history-list.tsx

Closes https://github.com/docmost/docmost/issues/906.

fix: hide page history action menu for can-view role

---

apps/client/src/features/space/components/sidebar/space-select.tsx

fix: Copy/move pages between spaces does not show spaces list

---

apps/client/src/features/editor/title-editor.tsx
apps/client/src/features/page/queries/page-query.ts
apps/client/src/features/page/services/page-service.ts
apps/client/src/features/page/tree/atoms/tree-data-atom.ts
apps/client/src/features/page/tree/components/space-tree.tsx
apps/client/src/features/page/tree/hooks/use-tree-mutation.ts
apps/client/src/features/page/tree/utils/utils.ts
apps/client/src/features/websocket/types/types.ts
apps/client/src/features/websocket/use-query-subscription.ts

- fix #1113 
- refactor: realtime page actions
- update tab "recently updated" in collab
- remember tree state when changing workspace
- navigate in overview if current page is in deleted node

fix: sidebar list when changing workspace

---

apps/client/package.json
apps/client/src/features/editor/extensions/extensions.ts
pnpm-lock.yaml

This fixed the word counter by using the [alfaaz](https://github.com/thecodrr/alfaaz) package to make it multilingual.
Closes https://github.com/docmost/docmost/issues/1225.

fix word counter (multilingual)

---

apps/client/src/features/editor/title-editor.tsx

When users are typing using an IME (Input Method Editor) in the `<TitleEditor>` component, pressing the `Enter` key is sometimes required to confirm the text conversion. However, in some cases, pressing `Enter` during composition is mistakenly interpreted as an input completion event, causing an unintended focus shift.
This issue primarily affects:
- **Japanese IME users** who frequently confirm input using the `Enter` key.
- **Chinese IME users** who manually confirm conversion using `Enter` (though many rely on the spacebar or automatic conversion).
To address this, the `isComposing` property is checked during `keydown` events. If `isComposing === true` when `Enter` is pressed, the default action is prevented to ensure that focus remains on the input field.
The `handleTitleKeyDown` …

Fix: Prevent premature focus change in TitleEditor when pressing Enter during IME composition

---

packages/editor-ext/src/lib/custom-code-block.ts

related to an issue I can't find anymore.  
Makes it so ctrl-a only selects content in a code block, which makes working with code blocks much easier, especially if transferring a mermaid diagram or something similar.

fix ctrl-a for codeblocks

---

apps/client/src/features/editor/page-editor.tsx

Handle token refresh without disrupting editor state by disconnecting, updating token, and reconnecting the HocuspocusProvider. This prevents scroll position resets and maintains user context during authentication token renewal.
It should also fix the massive reconnection loop on token expiration.

fix: seamlessly update editor collab token on expiration

---

apps/client/src/features/editor/components/code-block/mermaid-view.tsx

Reverts docmost/docmost#1397.
Leads to: Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component.
Will revisit this again.

Revert "feat: set mermaid theme based on computed color scheme"

---

apps/server/src/core/page/services/page.service.ts

In certain cases, duplicating a page in the same space led to position errors like this: `Error: a1B2R >= Zx1OH`
This should fix it.

fix: duplicate page position bug

---

apps/client/src/features/editor/components/code-block/mermaid-view.tsx

Hello,
after #1397 failed and you had to revert in #1412 - sorry for that. 
I now come with a second try, this time I have successfully tested it locally and it worked. Tried all transitions:
- light -> dark
- light -> auto
- dark -> light
- dark -> auto
- auto -> light
- auto -> dark
It works.
Note: There seems to be a slight (we're talking low low ms range) delay between docmost changing theme and mermaid, that is sometimes noticeable. I have tried it with Firefox.

fix: set mermaid theme based on computed color scheme

---

apps/client/src/features/editor/styles/print.css

This issue fixes #1464
The extra blank page was caused by Mantine’s <AppShell.Main> applying min-height: 100vh in print mode. In Chrome, 100vh maps to the full page box (~1056px) while the printable area is slightly smaller (~982px), which forced an overflow onto a second empty page.
I added min-height: auto to the existing class in 'print.css, so the container shrink-wraps to its content. This removes the phantom page without affecting normal screen layout.
https://github.com/user-attachments/assets/61b0798a-51f2-4028-94f2-d8107389f9ff

Fixing extra page bug on print

---

docker-compose.yml

In recents versions of docker the version tag in docker compose files are marked as deprecated.
see [docker formum](https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313)
A pull request on the docs repo has also been made [here](https://github.com/docmost/docs/pull/9)

Remove version from docker-compose.yml [deprecated]
