- apps/client/src/components/layouts/global/top-menu.tsx
- apps/client/src/features/editor/full-editor.tsx
- apps/client/src/features/editor/styles/editor.module.css
- apps/client/src/features/page/components/header/page-header-menu.tsx
- apps/client/src/features/user/atoms/current-user-atom.ts
- apps/client/src/features/user/components/page-width-pref.tsx
- apps/client/src/features/user/types/user.types.ts
- apps/client/src/pages/settings/account/account-preferences.tsx
- apps/server/src/core/user/dto/update-user.dto.ts
- apps/server/src/core/user/user.service.ts
- apps/server/src/database/repos/user/user.repo.ts
This PR adds the full page width user preference. All pages will open in full-width mode for the user if enabled.
Fixes: #26
> add full page width preference

- apps/client/src/features/editor/components/slash-menu/menu-items.ts
> added fuzzy matching logic for menu search

- apps/client/src/features/editor/components/image/image-view.tsx
- apps/client/src/features/editor/components/video/video-view.tsx
- apps/client/src/features/editor/styles/core.css
> fix media visibility in firefox

- apps/client/src/components/common/recent-changes.tsx
- apps/client/src/features/editor/styles/core.css
- apps/client/src/features/editor/styles/youtube.css
- apps/client/src/features/page/tree/components/space-tree.tsx
- apps/client/src/features/page/tree/hooks/use-tree-mutation.ts
- apps/client/src/features/search/search-spotlight.tsx
Closes https://github.com/docmost/docmost/issues/54 and https://github.com/docmost/docmost/issues/40
> Fix: missing tree, editor font and responsive recent pages

- apps/client/src/lib/api-client.ts
- apps/server/package.json
- apps/server/src/core/attachment/attachment.controller.ts
- apps/server/src/core/auth/strategies/jwt.strategy.ts
- apps/server/src/main.ts
- pnpm-lock.yaml
> make page attachments private

- apps/server/package.json
- apps/server/src/app.module.ts
- apps/server/src/common/interceptors/http-response.interceptor.ts
- apps/server/src/core/core.module.ts
- apps/server/src/database/database.module.ts
- apps/server/src/integrations/health/health.controller.ts
- apps/server/src/integrations/health/health.module.ts
- apps/server/src/integrations/health/postgres.health.ts
- apps/server/src/integrations/health/redis.health.ts
- apps/server/src/main.ts
- package.json
- pnpm-lock.yaml
Built upon PR #52 by @will2hew
This PR adds the `/api/health` endpoint.
I refactored the existing PR to make use of the more advanced [nestjs/terminus](https://www.npmjs.com/package/@nestjs/terminus) package.
> Add health check

- apps/server/src/database/repos/user/user.repo.ts
> make emails case-insensitive

- apps/client/src/features/workspace/components/members/components/workspace-members-table.tsx
> Fix #103: only owner can assign owner role

- apps/client/src/features/editor/extensions/extensions.ts
- apps/client/src/features/editor/page-editor.tsx
- apps/client/src/features/editor/styles/code.css
- apps/client/src/features/editor/styles/core.css
- apps/client/src/features/editor/styles/details.css
Should fix #135, #136 (disable spellcheck in code), #129 and #122.
> Fix: editor formatting

- Dockerfile
Needed to show changelog in Renovate PRs
https://docs.renovatebot.com/modules/datasource/docker/
> Add Source Label to Dockerfile

- apps/client/src/features/editor/components/code-block/code-block-view.tsx
- apps/client/src/features/editor/components/code-block/code-block.module.css
- apps/client/src/features/editor/extensions/extensions.ts
- apps/client/src/features/editor/styles/code.css
> feat: code block language selection

- apps/client/src/features/page/services/page-service.ts
- apps/server/src/core/attachment/attachment.controller.ts
- apps/server/src/integrations/export/export.controller.ts
Fixes https://github.com/docmost/docmost/issues/231.
> fix: page export failure when title contains non-ASCII characters

- apps/client/src/components/common/recent-changes.tsx
- apps/client/src/features/group/queries/group-query.ts
- apps/client/src/features/space/components/delete-space-modal.tsx
- apps/client/src/features/space/components/edit-space-form.tsx
- apps/client/src/features/space/components/space-details.tsx
- apps/client/src/features/space/queries/space-query.ts
- apps/client/src/features/space/services/space-service.ts
- apps/client/src/theme.ts
- apps/server/src/common/events/event.contants.ts
- apps/server/src/core/attachment/attachment.module.ts
- apps/server/src/core/attachment/processors/attachment.processor.ts
- apps/server/src/core/attachment/services/attachment.service.ts
- apps/server/src/core/space/services/space.service.ts
- apps/server/src/core/space/space.controller.ts
- apps/server/src/database/repos/attachment/attachment.repo.ts
- apps/server/src/database/repos/space/space-member.repo.ts
- apps/server/src/integrations/queue/constants/queue.constants.ts
- apps/server/src/integrations/queue/queue.module.ts
Closes https://github.com/docmost/docmost/issues/42.
> feat: delete space and edit space slug

- apps/client/src/App.tsx
- apps/client/src/features/auth/components/auth.module.css
- apps/client/src/features/auth/components/forgot-password-form.tsx
- apps/client/src/features/auth/components/login-form.tsx
- apps/client/src/features/auth/hooks/use-auth.ts
- apps/client/src/features/auth/services/auth-service.ts
- apps/client/src/features/auth/types/auth.types.ts
- apps/client/src/lib/app-route.ts
- apps/client/src/pages/auth/forgot-password.tsx
Here is the UI for forgot password. Solve [issue](https://github.com/docmost/docmost/issues/182) partially
See https://github.com/docmost/docmost/pull/250 for the backend
> feat(frontend): forgot password

- apps/client/src/features/editor/title-editor.tsx
- apps/client/src/features/page/tree/components/space-tree.tsx
- apps/client/src/features/page/tree/hooks/use-tree-mutation.ts
- apps/client/src/features/page/tree/utils/utils.ts
- apps/client/src/features/websocket/types/types.ts
- apps/client/src/features/websocket/use-query-subscription.ts
- apps/client/src/features/websocket/use-tree-socket.ts
Work towards improving the sidebar page tree sync across collaborators.
Closes: #308.
> fix: improve sidebar page tree syncing

- apps/client/src/features/editor/full-editor.tsx
Fix for https://github.com/docmost/docmost/discussions/449.
> fix: prevent default browser save behavior in editor

- apps/client/src/features/editor/full-editor.tsx
> Revert "fix: prevent default browser save behavior in editor"

- apps/client/src/features/page/tree/components/space-tree.tsx
- apps/client/src/features/page/tree/styles/tree.module.css
- apps/client/src/features/space/components/sidebar/space-sidebar.module.css
- apps/client/src/features/space/components/sidebar/space-sidebar.tsx
This pull request fixes the responsivity of the sidebar. (found on 0.4.1, and I could reproduce the issue on the latest main)
The tree items don't fill up the full height of the sidebar.
The items overflow so there are items which are not visible (the document "Last page" should be at the bottom of the list but it is below the viewport).
The sidebar consists of 3 sections: workspace selector, menu, tree list. In the current implementation each section takes up as much space as they need but inside the tree list section there is a fix height set.
The `treeContainer` class has a fix height of `68vh` which causes the elements to either flow over the viewport which renders them inaccessible or to not fill up the available space in the sidebar.
I left the first two sections unchanged and …
> Fix sidebar responsivity

- apps/client/src/components/layouts/global/app-shell.module.css
- apps/client/src/components/layouts/global/global-app-shell.tsx
- apps/client/src/components/layouts/global/hooks/atoms/sidebar-atom.ts
- apps/client/src/lib/jotai-helper.ts
https://github.com/user-attachments/assets/9a5fad66-9d38-486d-97f8-d32cf5e6a04f
> feat: resizable sidebar

- apps/client/src/features/editor/page-editor.tsx
Closes https://github.com/docmost/docmost/issues/461.
> fix: focus editor on bottom click

- apps/server/src/integrations/import/import.service.ts
> fix: index imported content

- apps/client/src/features/editor/title-editor.tsx
- apps/client/src/features/page/tree/components/space-tree.tsx
- apps/client/src/features/page/tree/hooks/use-tree-mutation.ts
- apps/client/src/features/websocket/types/types.ts
- apps/server/src/ws/ws.gateway.ts
Initial websocket room implementation for better workspace data privacy.
> feat: websocket rooms

- apps/client/src/features/page/tree/components/space-tree.tsx
- apps/client/src/features/websocket/use-tree-socket.ts
Closes https://github.com/docmost/docmost/issues/505.
> fix: tree sync bug

- packages/editor-ext/src/lib/custom-code-block.ts
Closes https://github.com/docmost/docmost/issues/500.
> feat: support tab key in code block

- apps/client/src/components/common/export-modal.tsx
- apps/client/src/features/page/components/header/page-header-menu.tsx
- apps/client/src/features/page/tree/components/space-tree.tsx
- apps/client/src/features/page/types/page.types.ts
- apps/client/src/features/space/components/sidebar/space-sidebar.tsx
- apps/client/src/features/space/components/space-details.tsx
- apps/client/src/features/space/services/space-service.ts
- apps/client/src/features/space/types/space.types.ts
- apps/client/src/lib/api-client.ts
- apps/server/src/collaboration/collaboration.util.ts
- apps/server/src/database/repos/page/page.repo.ts
- apps/server/src/integrations/export/dto/export-dto.ts
- apps/server/src/integrations/export/export.controller.ts
- apps/server/src/integrations/export/export.module.ts
- apps/server/src/integrations/export/export.service.ts
- apps/server/src/integrations/export/utils.ts
- package.json
- packages/editor-ext/src/lib/link.ts
- pnpm-lock.yaml
https://github.com/user-attachments/assets/25235fd8-0a26-4337-b45a-b80388ff7e3e
> feat: space export

- apps/client/src/features/page/components/page-import-modal.tsx
Only show markdown files in file selection.
> fix: markdown import file button

- apps/server/src/integrations/environment/environment.validation.ts
Fixes https://github.com/docmost/docmost/issues/547,  https://github.com/docmost/docmost/issues/171 and https://github.com/docmost/docmost/issues/499.
> fix: postgres and redis url validation

- apps/server/src/integrations/export/turndown-utils.ts
- apps/server/src/integrations/import/utils/marked.utils.ts
- apps/server/src/integrations/import/utils/math-block.marked.ts
- apps/server/src/integrations/import/utils/math-inline.marked.ts
Fix markdown math import.
Resolves https://github.com/docmost/docmost/discussions/526.
> fix: markdown math import

- apps/server/src/core/attachment/attachment.controller.ts
Fixes https://github.com/docmost/docmost/discussions/561.
> fix: prevent CDNs from caching attachments

- apps/client/src/lib/api-client.ts
- apps/client/src/lib/config.ts
* fix 401 redirect in auth routes
* fix config getter
> fix 401 redirect in auth routes

- apps/client/src/features/user/components/account-language.tsx
- apps/server/src/core/workspace/services/workspace-invitation.service.ts
- apps/server/src/database/repos/user/user.repo.ts
* Set default language on invitation signup
* Default language selection to en-US if locale is undefined (Client)
> fix: default language on invitation signup

- apps/client/src/features/space/components/sidebar/switch-space.tsx
#662 
| Before fix| After fix|
|--------|--------|
| ![change-space-old](https://github.com/user-attachments/assets/e1ad547d-d1fb-445c-978f-d4ea485f81df)| ![change-space-new](https://github.com/user-attachments/assets/7d3bb6e4-865d-4daf-aecf-9106915ddc0c)|
> fix: switch space bug

- apps/server/src/integrations/static/static.module.ts
On first startup, the `` placeholder in the `index.html` gets replaced with the .env variables. Updates to the .env file will not reflect in the `index.html` file because the `` placeholder will no longer exist.
This PR fixes the issue by copying  the `index.html` to a temporary `index-template.html`. We read from the temporary file, replace the placeholder and update the `index.html`. This way, `` placeholder will always be present.
> fix client side env variable refresh

- apps/client/public/locales/en-US/translation.json
- apps/client/src/features/editor/components/bubble-menu/bubble-menu.tsx
- apps/client/src/features/editor/components/bubble-menu/text-alignment-selector.tsx
> feat: add text alignment

- apps/server/package.json
- apps/server/src/app.module.ts
- apps/server/src/collaboration/server/collab-app.module.ts
- apps/server/src/collaboration/server/collab-main.ts
- apps/server/src/common/sentry/instrument.ts
- apps/server/src/main.ts
Sentry integration.
New environment variable:
```
SENTRY_DSN=
```
> feat: sentry

- apps/server/src/core/comment/comment.service.ts
- apps/server/src/core/workspace/services/workspace.service.ts
`await` before checking if the value is truthy.
> fix: add missing awaits

- apps/server/src/database/database.module.ts
> Add debug db option in dev mode

- apps/server/src/collaboration/collaboration.gateway.ts
- apps/server/src/common/helpers/utils.ts
- apps/server/src/integrations/queue/queue.module.ts
- apps/server/src/ws/adapter/ws-redis.adapter.ts
closes https://github.com/docmost/docmost/issues/534#issuecomment-2686172185
> feat: adding family 6 in uri to configure for both 4 and 6

- apps/client/package.json
- apps/client/src/features/editor/full-editor.tsx
- apps/client/src/features/editor/styles/core.css
- apps/client/src/features/editor/styles/editor.module.css
- pnpm-lock.yaml
The drag handle disappears when you try to grab it.
I fixed this by adding padding to the prosemirror css class.
Closes https://github.com/docmost/docmost/discussions/797.
> fix drag handle visibility

- apps/client/src/features/editor/page-editor.tsx
This PR aims to improve the page experience when users navigate between pages or return back to previously opened pages.
> fix editor flickers

- apps/client/package.json
- apps/client/public/locales/en-US/translation.json
- apps/client/src/features/editor/extensions/extensions.ts
- apps/client/src/features/page/components/header/page-header-menu.tsx
- apps/client/src/features/page/types/page.types.ts
- apps/server/src/core/page/page.controller.ts
- apps/server/src/database/repos/page/page.repo.ts
- pnpm-lock.yaml
> feat: add page stats to page menu

- apps/client/package.json
- apps/client/src/features/editor/title-editor.tsx
- apps/client/src/features/websocket/use-tree-socket.ts
- apps/client/src/lib/local-emitter.ts
- pnpm-lock.yaml
This PR aims to properly address https://github.com/docmost/docmost/issues/850, https://github.com/docmost/docmost/issues/223.
> fix: page title editor bugs

- apps/client/src/features/editor/components/attachment/upload-attachment-action.tsx
- apps/client/src/features/editor/components/common/editor-paste-handler.tsx
- apps/client/src/features/editor/components/slash-menu/menu-items.ts
- apps/client/src/features/editor/components/video/video-view.tsx
- packages/editor-ext/src/lib/attachment/attachment-upload.ts
- packages/editor-ext/src/lib/image/image-upload.ts
- packages/editor-ext/src/lib/media-utils.ts
- packages/editor-ext/src/lib/video/video-upload.ts
- multi-file paste support
- allow media files (image/videos) to be attachments
- insert trailing node if file upload placeholder is at the end of the editor
- fix video align
> feat: enhance editor uploads

- apps/server/package.json
- apps/server/src/collaboration/listeners/history.listener.ts
- apps/server/src/core/workspace/services/workspace-invitation.service.ts
- apps/server/src/integrations/queue/constants/queue.constants.ts
- apps/server/src/integrations/queue/constants/queue.interface.ts
- apps/server/src/integrations/queue/processors/backlinks.processor.ts
- apps/server/src/integrations/queue/queue.module.ts
> feat: billing sync (cloud)

- apps/client/src/components/ui/emoji-picker.tsx
Reverts docmost/docmost#894.
It scrolls the editor to top.
> Revert "feat: auto focus emoji-picker search when opened"

- apps/client/src/features/auth/queries/auth-query.tsx
- apps/client/src/features/editor/page-editor.tsx
Fix collab token refresh issue which leads to collab editor reconnection loop.
> fix: collab editor retry loop

- apps/client/package.json
- apps/client/public/locales/en-US/translation.json
- apps/client/src/components/settings/app-version.tsx
- apps/client/src/components/settings/settings-sidebar.tsx
- apps/client/src/features/workspace/queries/workspace-query.ts
- apps/client/src/features/workspace/services/workspace-service.ts
- apps/client/src/features/workspace/types/workspace.types.ts
- apps/server/src/integrations/security/security.module.ts
- apps/server/src/integrations/security/version.controller.ts
- apps/server/src/integrations/security/version.service.ts
- pnpm-lock.yaml
New `/api/version` endpoint.
```json
{
"data": {
"currentVersion": "0.8.4",
"latestVersion": "0.8.4",
"releaseUrl": "https://github.com/docmost/docmost/releases"
},
"success": true,
"status": 200
}
```
> feat: add version check

- apps/client/src/features/editor/components/bubble-menu/color-selector.tsx
- apps/server/package.json
- apps/server/src/app.module.ts
- apps/server/src/integrations/environment/environment.service.ts
- apps/server/src/integrations/telemetry/telemetry.module.ts
- apps/server/src/integrations/telemetry/telemetry.service.ts
- pnpm-lock.yaml
New environment variable to disable telemetry:
```
DISABLE_TELEMETRY=true
```
> telemetry module

- apps/client/package.json
- pnpm-lock.yaml
> Revert "switch to vite rolldown"

- apps/client/src/features/search/components/search-control.module.css
- apps/client/src/features/search/components/search-control.tsx
- apps/client/src/features/search/constants.ts
- apps/client/src/features/search/queries/search-query.ts
- apps/client/src/features/search/search-spotlight.tsx
- apps/client/src/features/search/services/search-service.ts
- apps/client/src/features/search/share-search-spotlight.tsx
- apps/client/src/features/search/types/search.types.ts
- apps/client/src/features/share/components/share-shell.tsx
- apps/client/src/features/share/components/shared-tree.tsx
- apps/client/src/features/share/utils.ts
- apps/client/src/features/space/components/sidebar/space-sidebar.tsx
- apps/server/src/common/helpers/prosemirror/utils.ts
- apps/server/src/core/search/dto/search.dto.ts
- apps/server/src/core/search/search.controller.ts
- apps/server/src/core/search/search.service.ts
- apps/server/src/core/share/share.service.ts
Aims to address https://github.com/docmost/docmost/issues/1052, https://github.com/docmost/docmost/issues/1053, https://github.com/docmost/docmost/issues/1056, https://github.com/docmost/docmost/issues/1054 and https://github.com/docmost/docmost/issues/1059.
> feat: enhance public sharing

- apps/server/src/database/repos/page/page.repo.ts
Fix for https://github.com/docmost/docmost/issues/1080.
> fix: page export with sub-pages

- apps/server/src/collaboration/collaboration.module.ts
- apps/server/src/collaboration/extensions/persistence.extension.ts
- apps/server/src/main.ts
Handle unhandled exceptions to prevent unnecessary crashes.
> fix: handle unhandled exceptions

- apps/server/src/collaboration/collaboration.util.ts
> [Issue-1091] fix alignment in shared page

- apps/client/src/features/editor/title-editor.tsx
- apps/client/src/features/page/queries/page-query.ts
- close #482 
| Before| After|
|--------|--------|
| ![before](https://github.com/user-attachments/assets/b5cc0753-7ed1-4dff-811f-e8d1f1c31049)| ![after](https://github.com/user-attachments/assets/e0cdf12e-1d40-4cfe-ab5c-9cc3073d2ff8)|
> fix: title update

- apps/client/src/features/comment/components/comment-dialog.tsx
- apps/client/src/features/comment/components/comment-editor.tsx
- apps/client/src/features/comment/components/comment-list-item.tsx
- apps/client/src/features/comment/components/comment-list.tsx
- apps/client/src/features/comment/components/comment.module.css
- apps/client/src/features/editor/page-editor.tsx
- apps/client/src/features/editor/styles/core.css
- apps/client/src/features/websocket/types/types.ts
- apps/client/src/features/websocket/use-query-subscription.ts
> feat: realtime comments

- apps/client/src/features/editor/components/mention/mention-list.tsx
> feat: create new page from mention

- apps/client/src/features/comment/components/comment-actions.tsx
- apps/client/src/features/comment/components/comment-dialog.tsx
- apps/client/src/features/comment/components/comment-editor.tsx
- apps/client/src/features/comment/components/comment-list-item.tsx
- apps/client/src/features/comment/components/comment-list.tsx
- apps/client/src/features/comment/components/comment.module.css
- apps/client/src/features/editor/components/emoji-menu/render-emoji-items.ts
- Comment editor emoji picker
- Allow submitting comment via CTRL-ENTER #1073
> feat: comment editor emoji picker and ctrl+enter action

- apps/client/src/features/editor/components/table/table-menu.tsx
> feat: toggle table header row and column

- apps/client/src/features/editor/components/bubble-menu/bubble-menu.tsx
- apps/client/src/features/editor/components/bubble-menu/link-selector.tsx
> fix: make link popup work on safari

- apps/client/src/features/editor/page-editor.tsx
- apps/server/src/collaboration/extensions/persistence.extension.ts
> feat: Ctrl/Cmd+S: prevent 'Save As' dialog

- apps/client/src/features/space/components/multi-member-select.tsx
- apps/server/src/core/search/search.service.ts
- Added email field to user items mapping
- Updated renderMultiSelectOption to show email in smaller, dimmed text
> feat: display user email below name in multi-member-select dropdown

- apps/server/package.json
- apps/server/src/integrations/import/services/import-attachment.service.ts
- pnpm-lock.yaml
> Enhance zip imports

- apps/client/src/features/page/tree/components/space-tree.tsx
The tree API atom state is not always set, which makes it impossible to create new pages sometimes.
This should fix it.
> fix page tree api atom

- apps/server/src/core/attachment/attachment.controller.ts
Make sure public avatar path is a valid UUID.
> fix: validate public avatar path

- apps/client/src/App.tsx
- apps/client/src/features/page/trash/components/trash.tsx
- apps/client/src/pages/space/space-trash.tsx
- apps/server/src/core/page/dto/deleted-page.dto.ts
- apps/server/src/core/page/page.controller.ts
Trash list should not be visible to the "Can view" permission.
> fix: hide trash from can view permission

- apps/client/src/components/ui/emoji-picker.tsx
- apps/client/src/features/editor/components/callout/callout-menu.tsx
- apps/client/src/features/editor/components/callout/callout-view.tsx
- packages/editor-ext/src/lib/callout/callout.ts
> Add custom emoji to callout
